// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pinnedRepository

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PinnedRepositoryClient is the client API for PinnedRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinnedRepositoryClient interface {
	Get(ctx context.Context, in *PinnedRepository, opts ...grpc.CallOption) (*PinnedRepository, error)
}

type pinnedRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewPinnedRepositoryClient(cc grpc.ClientConnInterface) PinnedRepositoryClient {
	return &pinnedRepositoryClient{cc}
}

var pinnedRepositoryGetStreamDesc = &grpc.StreamDesc{
	StreamName: "Get",
}

func (c *pinnedRepositoryClient) Get(ctx context.Context, in *PinnedRepository, opts ...grpc.CallOption) (*PinnedRepository, error) {
	out := new(PinnedRepository)
	err := c.cc.Invoke(ctx, "/pinnedRepository.PinnedRepository/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PinnedRepositoryService is the service API for PinnedRepository service.
// Fields should be assigned to their respective handler implementations only before
// RegisterPinnedRepositoryService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type PinnedRepositoryService struct {
	Get func(context.Context, *PinnedRepository) (*PinnedRepository, error)
}

func (s *PinnedRepositoryService) get(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinnedRepository)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/pinnedRepository.PinnedRepository/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Get(ctx, req.(*PinnedRepository))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterPinnedRepositoryService registers a service implementation with a gRPC server.
func RegisterPinnedRepositoryService(s grpc.ServiceRegistrar, srv *PinnedRepositoryService) {
	srvCopy := *srv
	if srvCopy.Get == nil {
		srvCopy.Get = func(context.Context, *PinnedRepository) (*PinnedRepository, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "pinnedRepository.PinnedRepository",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Get",
				Handler:    srvCopy.get,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "pinnedRepository/pinnedRepository.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewPinnedRepositoryService creates a new PinnedRepositoryService containing the
// implemented methods of the PinnedRepository service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewPinnedRepositoryService(s interface{}) *PinnedRepositoryService {
	ns := &PinnedRepositoryService{}
	if h, ok := s.(interface {
		Get(context.Context, *PinnedRepository) (*PinnedRepository, error)
	}); ok {
		ns.Get = h.Get
	}
	return ns
}

// UnstablePinnedRepositoryService is the service API for PinnedRepository service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstablePinnedRepositoryService interface {
	Get(context.Context, *PinnedRepository) (*PinnedRepository, error)
}
