// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: pinnedRepository/pinnedRepository.proto

package pinnedRepository

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestType int32

const (
	RequestType_STANDARD RequestType = 0
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "STANDARD",
	}
	RequestType_value = map[string]int32{
		"STANDARD": 0,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_pinnedRepository_pinnedRepository_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_pinnedRepository_pinnedRepository_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_pinnedRepository_pinnedRepository_proto_rawDescGZIP(), []int{0}
}

type PinnedRepository struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DatabaseId  int32    `protobuf:"varint,4,opt,name=databaseId,proto3" json:"databaseId,omitempty"`
	Url         string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt   string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   string   `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	IsCurrent   bool     `protobuf:"varint,8,opt,name=isCurrent,proto3" json:"isCurrent,omitempty"`
	TagIds      []string `protobuf:"bytes,9,rep,name=tagIds,proto3" json:"tagIds,omitempty"`
}

func (x *PinnedRepository) Reset() {
	*x = PinnedRepository{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinnedRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinnedRepository) ProtoMessage() {}

func (x *PinnedRepository) ProtoReflect() protoreflect.Message {
	mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinnedRepository.ProtoReflect.Descriptor instead.
func (*PinnedRepository) Descriptor() ([]byte, []int) {
	return file_pinnedRepository_pinnedRepository_proto_rawDescGZIP(), []int{0}
}

func (x *PinnedRepository) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PinnedRepository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinnedRepository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PinnedRepository) GetDatabaseId() int32 {
	if x != nil {
		return x.DatabaseId
	}
	return 0
}

func (x *PinnedRepository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PinnedRepository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PinnedRepository) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PinnedRepository) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *PinnedRepository) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type SyncPinnedRepositoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestType RequestType `protobuf:"varint,1,opt,name=requestType,proto3,enum=pinnedRepository.RequestType" json:"requestType,omitempty"`
}

func (x *SyncPinnedRepositoryRequest) Reset() {
	*x = SyncPinnedRepositoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPinnedRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPinnedRepositoryRequest) ProtoMessage() {}

func (x *SyncPinnedRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPinnedRepositoryRequest.ProtoReflect.Descriptor instead.
func (*SyncPinnedRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_pinnedRepository_pinnedRepository_proto_rawDescGZIP(), []int{1}
}

func (x *SyncPinnedRepositoryRequest) GetRequestType() RequestType {
	if x != nil {
		return x.RequestType
	}
	return RequestType_STANDARD
}

type SyncPinnedRepositoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SyncPinnedRepositoryResponse) Reset() {
	*x = SyncPinnedRepositoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPinnedRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPinnedRepositoryResponse) ProtoMessage() {}

func (x *SyncPinnedRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pinnedRepository_pinnedRepository_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPinnedRepositoryResponse.ProtoReflect.Descriptor instead.
func (*SyncPinnedRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_pinnedRepository_pinnedRepository_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPinnedRepositoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pinnedRepository_pinnedRepository_proto protoreflect.FileDescriptor

var file_pinnedRepository_pinnedRepository_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x2f, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xfc, 0x01, 0x0a, 0x10,
	0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x49, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x67, 0x49, 0x64, 0x73, 0x22, 0x5e, 0x0a, 0x1b, 0x73, 0x79,
	0x6e, 0x63, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a, 0x1c, 0x73, 0x79,
	0x6e, 0x63, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x2a, 0x1b, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x4e, 0x44, 0x41, 0x52, 0x44, 0x10,
	0x00, 0x32, 0x7b, 0x0a, 0x10, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x67, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2d, 0x2e,
	0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x70,
	0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4b,
	0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x65, 0x68,
	0x75, 0x64, 0x61, 0x6d, 0x61, 0x6b, 0x61, 0x72, 0x6f, 0x76, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x2d, 0x73, 0x69, 0x74, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pinnedRepository_pinnedRepository_proto_rawDescOnce sync.Once
	file_pinnedRepository_pinnedRepository_proto_rawDescData = file_pinnedRepository_pinnedRepository_proto_rawDesc
)

func file_pinnedRepository_pinnedRepository_proto_rawDescGZIP() []byte {
	file_pinnedRepository_pinnedRepository_proto_rawDescOnce.Do(func() {
		file_pinnedRepository_pinnedRepository_proto_rawDescData = protoimpl.X.CompressGZIP(file_pinnedRepository_pinnedRepository_proto_rawDescData)
	})
	return file_pinnedRepository_pinnedRepository_proto_rawDescData
}

var file_pinnedRepository_pinnedRepository_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pinnedRepository_pinnedRepository_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pinnedRepository_pinnedRepository_proto_goTypes = []interface{}{
	(RequestType)(0),                     // 0: pinnedRepository.RequestType
	(*PinnedRepository)(nil),             // 1: pinnedRepository.pinnedRepository
	(*SyncPinnedRepositoryRequest)(nil),  // 2: pinnedRepository.syncPinnedRepositoryRequest
	(*SyncPinnedRepositoryResponse)(nil), // 3: pinnedRepository.syncPinnedRepositoryResponse
}
var file_pinnedRepository_pinnedRepository_proto_depIdxs = []int32{
	0, // 0: pinnedRepository.syncPinnedRepositoryRequest.requestType:type_name -> pinnedRepository.RequestType
	2, // 1: pinnedRepository.PinnedRepository.Sync:input_type -> pinnedRepository.syncPinnedRepositoryRequest
	3, // 2: pinnedRepository.PinnedRepository.Sync:output_type -> pinnedRepository.syncPinnedRepositoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pinnedRepository_pinnedRepository_proto_init() }
func file_pinnedRepository_pinnedRepository_proto_init() {
	if File_pinnedRepository_pinnedRepository_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pinnedRepository_pinnedRepository_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinnedRepository); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pinnedRepository_pinnedRepository_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPinnedRepositoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pinnedRepository_pinnedRepository_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPinnedRepositoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pinnedRepository_pinnedRepository_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinnedRepository_pinnedRepository_proto_goTypes,
		DependencyIndexes: file_pinnedRepository_pinnedRepository_proto_depIdxs,
		EnumInfos:         file_pinnedRepository_pinnedRepository_proto_enumTypes,
		MessageInfos:      file_pinnedRepository_pinnedRepository_proto_msgTypes,
	}.Build()
	File_pinnedRepository_pinnedRepository_proto = out.File
	file_pinnedRepository_pinnedRepository_proto_rawDesc = nil
	file_pinnedRepository_pinnedRepository_proto_goTypes = nil
	file_pinnedRepository_pinnedRepository_proto_depIdxs = nil
}
